# This is a basic workflow to help you get started with Actions

name: Test

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["pypy3"]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - uses: "actions/setup-python@v2"
      with:
        python-version: "${{ matrix.python-version }}"

    - name: "Install dependencies"
      run: |
        python -VV
        python -m site
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install --upgrade coverage[toml] virtualenv tox tox-gh-actions

    - name: "Run tox targets for ${{ matrix.python-version }}"
      run: |
        ls -lrt
        python -m tox -c tox.ini
